### ISSUE TITLE
Error: listen EADDRINUSE 

### ISSUE THREAD

**Issue by disarticulate** [ice-services/moleculer#148]
Trying to setup a test using the npm run ci

keep getting 
```
Error: listen EADDRINUSE :::9120
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1496:7)
    at new TCPPool (/home/cy/micro/downloader/node_modules/webtorrent/lib/tcp-pool.js:45:15)
    at new WebTorrent (/home/cy/micro/downloader/node_modules/webtorrent/index.js:114:21)
    at Object.<anonymous> (/home/cy/micro/downloader/lib/torrents.js:28:16)
    at Runtime._execModule (/home/cy/micro/downloader/node_modules/jest-runtime/build/index.js:513:13)
    at Runtime.requireModule (/home/cy/micro/downloader/node_modules/jest-runtime/build/index.js:329:14)
```
On the second run through. Which means this doesn't appear to shut down the server:
```
beforeAll(() => {
  	console.log('starting')
	return broker.start();
});

afterAll(() => {
  	console.log('stopping')
	return broker.stop();
});
```
The console outputs both starting and stopping during the test, so I know they're both firing. I'm using the nano service template, which doesn't seem to work.
*** Expectation:
`broker.stop()`

should remove the port listener

**Comment by disarticulate** [comment]
wrong library isdsue
