### ISSUE TITLE
Runaway promises in transit module

### ISSUE THREAD

**Issue by deividasjackus** [ice-services/moleculer#55]
While using Redis transporter:

```
(node:10664) Warning: a promise was created in a handler at \node_modules\moleculer\src\transit.js:73:11 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (\node_modules\bluebird\js\release\promise.js:79:10)

(node:10664) Warning: a promise was created in a handler at \node_modules\moleculer\src\transit.js:76:21 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (\node_modules\bluebird\js\release\promise.js:79:10)

(node:10664) Warning: a promise was created in a handler at \node_modules\moleculer\src\transit.js:77:21 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (\node_modules\bluebird\js\release\promise.js:79:10)
```

**Comment by icebob** [comment]
Thanks, I'm going to fix it.

**Comment by icebob** [comment]
I couldn't reproduce it, but I hope https://github.com/ice-services/moleculer/commit/2fc5fdd6c8c75ddeff8c0ecc357d7a780e448472 is fixed it :)

**Comment by deividasjackus** [comment]
Will try to reproduce it within the hour.

**Comment by deividasjackus** [comment]
Seems to be fixed now 👏
